// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GTRDbContext))]
    [Migration("20230221084922_PRODUCT_SEED")]
    partial class PRODUCT_SEED
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "en",
                            Name = "Hoppe Group"
                        },
                        new
                        {
                            Id = 2,
                            Country = "en",
                            Name = "Feil, Ryan and Lueilwitz"
                        },
                        new
                        {
                            Id = 3,
                            Country = "en",
                            Name = "Schumm LLC"
                        },
                        new
                        {
                            Id = 4,
                            Country = "en",
                            Name = "Hettinger - Schamberger"
                        },
                        new
                        {
                            Id = 5,
                            Country = "en",
                            Name = "Dickinson, Schuster and Gorczany"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductBarcode")
                        .HasColumnType("int");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 2,
                            CategoryId = 3,
                            Code = 3037,
                            ColorName = "black",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModelName = "Awesome",
                            Name = "Cheese",
                            ProductBarcode = 563621,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Intelligent Soft Bike"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            CategoryId = 3,
                            Code = 2166,
                            ColorName = "orange",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ModelName = "Tasty",
                            Name = "Computer",
                            ProductBarcode = 687075,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Refined Soft Chicken"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 5,
                            Code = 8144,
                            ColorName = "orchid",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModelName = "Handmade",
                            Name = "Car",
                            ProductBarcode = 782235,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Fantastic Granite Ball"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 5,
                            CategoryId = 5,
                            Code = 1454,
                            ColorName = "olive",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ModelName = "Unbranded",
                            Name = "Soap",
                            ProductBarcode = 139311,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Tasty Soft Ball"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 2,
                            Code = 9186,
                            ColorName = "magenta",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModelName = "Generic",
                            Name = "Keyboard",
                            ProductBarcode = 674778,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Licensed Cotton Cheese"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 2,
                            Code = 7619,
                            ColorName = "purple",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModelName = "Ergonomic",
                            Name = "Tuna",
                            ProductBarcode = 232041,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Practical Granite Pants"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            CategoryId = 4,
                            Code = 4247,
                            ColorName = "ivory",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModelName = "Handmade",
                            Name = "Chicken",
                            ProductBarcode = 558315,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Rustic Granite Pizza"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            CategoryId = 2,
                            Code = 9395,
                            ColorName = "plum",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModelName = "Sleek",
                            Name = "Chicken",
                            ProductBarcode = 612194,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Generic Soft Car"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 2,
                            Code = 5135,
                            ColorName = "violet",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ModelName = "Licensed",
                            Name = "Mouse",
                            ProductBarcode = 962006,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Small Frozen Cheese"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            CategoryId = 4,
                            Code = 2057,
                            ColorName = "azure",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModelName = "Refined",
                            Name = "Tuna",
                            ProductBarcode = 299761,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Intelligent Fresh Hat"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 4,
                            Code = 8429,
                            ColorName = "turquoise",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ModelName = "Refined",
                            Name = "Mouse",
                            ProductBarcode = 533278,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Gorgeous Rubber Shirt"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 4,
                            CategoryId = 5,
                            Code = 3531,
                            ColorName = "azure",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModelName = "Awesome",
                            Name = "Keyboard",
                            ProductBarcode = 447109,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Tasty Steel Salad"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 5,
                            CategoryId = 1,
                            Code = 1909,
                            ColorName = "yellow",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModelName = "Small",
                            Name = "Cheese",
                            ProductBarcode = 992334,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Incredible Cotton Ball"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 2,
                            CategoryId = 4,
                            Code = 5290,
                            ColorName = "violet",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModelName = "Sleek",
                            Name = "Computer",
                            ProductBarcode = 300133,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Tasty Steel Fish"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CategoryId = 3,
                            Code = 9348,
                            ColorName = "teal",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModelName = "Unbranded",
                            Name = "Towels",
                            ProductBarcode = 421449,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Rustic Steel Chicken"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            CategoryId = 3,
                            Code = 2202,
                            ColorName = "purple",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModelName = "Small",
                            Name = "Car",
                            ProductBarcode = 967950,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Practical Fresh Gloves"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            CategoryId = 5,
                            Code = 4291,
                            ColorName = "mint green",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModelName = "Generic",
                            Name = "Keyboard",
                            ProductBarcode = 116317,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Intelligent Rubber Shoes"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            CategoryId = 3,
                            Code = 2799,
                            ColorName = "turquoise",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModelName = "Ergonomic",
                            Name = "Soap",
                            ProductBarcode = 700839,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Refined Fresh Salad"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            CategoryId = 5,
                            Code = 1019,
                            ColorName = "grey",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModelName = "Gorgeous",
                            Name = "Chips",
                            ProductBarcode = 433543,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Rustic Cotton Sausages"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 2,
                            CategoryId = 4,
                            Code = 7950,
                            ColorName = "olive",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModelName = "Refined",
                            Name = "Sausages",
                            ProductBarcode = 139559,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Fantastic Wooden Shoes"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 4,
                            CategoryId = 5,
                            Code = 1289,
                            ColorName = "violet",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ModelName = "Handmade",
                            Name = "Salad",
                            ProductBarcode = 677428,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Incredible Fresh Shirt"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 4,
                            CategoryId = 3,
                            Code = 8179,
                            ColorName = "purple",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ModelName = "Refined",
                            Name = "Shirt",
                            ProductBarcode = 549691,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Handcrafted Rubber Salad"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            CategoryId = 5,
                            Code = 8220,
                            ColorName = "orchid",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ModelName = "Incredible",
                            Name = "Cheese",
                            ProductBarcode = 465836,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Fantastic Granite Cheese"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 4,
                            CategoryId = 3,
                            Code = 5185,
                            ColorName = "azure",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ModelName = "Fantastic",
                            Name = "Soap",
                            ProductBarcode = 598330,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Handcrafted Concrete Pizza"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            CategoryId = 1,
                            Code = 3078,
                            ColorName = "pink",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModelName = "Incredible",
                            Name = "Gloves",
                            ProductBarcode = 790613,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Practical Wooden Soap"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 4,
                            CategoryId = 4,
                            Code = 4928,
                            ColorName = "azure",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ModelName = "Sleek",
                            Name = "Fish",
                            ProductBarcode = 318454,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Licensed Metal Table"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 1,
                            CategoryId = 3,
                            Code = 9443,
                            ColorName = "turquoise",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModelName = "Small",
                            Name = "Bacon",
                            ProductBarcode = 762263,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Unbranded Wooden Cheese"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 5,
                            CategoryId = 1,
                            Code = 5308,
                            ColorName = "orange",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModelName = "Tasty",
                            Name = "Bike",
                            ProductBarcode = 849150,
                            SizeName = "",
                            UserId = 2,
                            VariantName = "Refined Steel Tuna"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 1,
                            CategoryId = 1,
                            Code = 9238,
                            ColorName = "violet",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModelName = "Tasty",
                            Name = "Soap",
                            ProductBarcode = 497283,
                            SizeName = "",
                            UserId = 1,
                            VariantName = "Practical Frozen Shirt"
                        });
                });

            modelBuilder.Entity("DAL.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "abysswalkr01@gmail.com",
                            Name = "Shanto",
                            Password = "$2b$10$cD7C/yFQOVM1Az6X2eB0KevUWOYcx.ieMS0cSfs83tEOIvJBbPIF2"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alex@gmail.com",
                            Name = "Alex",
                            Password = "$2b$10$cBdRhA/4CzILjJd0YIqoYOwK3Rus2g4RULdfKWal./1n9GSQqGcMW"
                        });
                });

            modelBuilder.Entity("DAL.Entities.Product", b =>
                {
                    b.HasOne("DAL.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.Token", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
